/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store.ui;

import java.awt.Color;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import store.classes.Customer;
import store.classes.Store;

/**
 *
 * @author IT676
 */
public class LoginRegisterWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginRegisterWindow
     */
    Store currentStore;
    
    public LoginRegisterWindow(Store store) {
        
        this();
       
        this.currentStore = store;
      
    }
    
    public LoginRegisterWindow() {
        initComponents();
        
        customSettings();
        
        ButtonGroup group = new ButtonGroup();
        group.add(loginRB);
        group.add(registerRB);

        //we need to disable the rgister panel at the begning 
        setPanelEnable(registerPanel, false);

        //ok now when we click on a btn we need to activate it 
    }
    
    public static void setPanelEnable(JPanel panel, boolean isEnable) {
        
        panel.setEnabled(isEnable);//yes or no

        //not we need to disable or enable all its comonents
        Component[] components = panel.getComponents();

        //loop on all components  and disable/enable them
        for (Component comp : components) {
            
            comp.setEnabled(isEnable);
        }
        
    }
    
    public final void customSettings() {
        
        this.getContentPane().setBackground(Color.WHITE);
        
        this.setLocation(450, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameTxtFRegister = new javax.swing.JTextField();
        passwordTxtFRegister = new javax.swing.JPasswordField();
        registerBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fullNameTxtF = new javax.swing.JTextField();
        loginPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userNameTxtF = new javax.swing.JTextField();
        passwordTxtF = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        registerRB = new javax.swing.JRadioButton();
        loginRB = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dreams Electronics Store-Login/Register");
        setResizable(false);
        setSize(new java.awt.Dimension(750, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(3, 169, 244));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login or Create a New Account");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome To The Dreams Electronics Store");
        headerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, -1));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 70));

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 169, 244), 1, true));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(3, 169, 244));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/images/password-icon.png"))); // NOI18N
        jLabel2.setText("Password:");
        registerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(3, 169, 244));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/images/email-icon.png"))); // NOI18N
        jLabel4.setText("User Name: ");
        registerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, -1, -1));

        userNameTxtFRegister.setForeground(new java.awt.Color(3, 169, 244));
        registerPanel.add(userNameTxtFRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 55, 160, -1));

        passwordTxtFRegister.setForeground(new java.awt.Color(3, 169, 244));
        registerPanel.add(passwordTxtFRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, -1));

        registerBtn.setBackground(new java.awt.Color(255, 255, 255));
        registerBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(3, 169, 244));
        registerBtn.setText("Register");
        registerPanel.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel7.setForeground(new java.awt.Color(3, 169, 244));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/images/account-icon.png"))); // NOI18N
        jLabel7.setText("Full Name:");
        registerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        fullNameTxtF.setForeground(new java.awt.Color(3, 169, 244));
        registerPanel.add(fullNameTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, -1));

        getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 330, 180));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 169, 244), 1, true));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(3, 169, 244));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/images/password-icon.png"))); // NOI18N
        jLabel5.setText("Password:");
        loginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel6.setForeground(new java.awt.Color(3, 169, 244));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/images/account-icon.png"))); // NOI18N
        jLabel6.setText("User Name: ");
        loginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        userNameTxtF.setForeground(new java.awt.Color(3, 169, 244));
        loginPanel.add(userNameTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, -1));

        passwordTxtF.setForeground(new java.awt.Color(3, 169, 244));
        loginPanel.add(passwordTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(3, 169, 244));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 100, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 180));

        registerRB.setBackground(new java.awt.Color(255, 255, 255));
        registerRB.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        registerRB.setForeground(new java.awt.Color(3, 169, 244));
        registerRB.setText("Register");
        registerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerRBActionPerformed(evt);
            }
        });
        getContentPane().add(registerRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        loginRB.setBackground(new java.awt.Color(255, 255, 255));
        loginRB.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        loginRB.setForeground(new java.awt.Color(3, 169, 244));
        loginRB.setSelected(true);
        loginRB.setText("Login");
        loginRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRBActionPerformed(evt);
            }
        });
        getContentPane().add(loginRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel1.setBackground(new java.awt.Color(3, 169, 244));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 830, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRBActionPerformed

        //enable login panel 
        setPanelEnable(loginPanel, true);

        //disable register panel
        setPanelEnable(registerPanel, false);
        

    }//GEN-LAST:event_loginRBActionPerformed

    private void registerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerRBActionPerformed

        //disable login panel 
        setPanelEnable(loginPanel, false);

        //enable register panel
        setPanelEnable(registerPanel, true);

    }//GEN-LAST:event_registerRBActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        //validate the input 
        if (isEmpty(userNameTxtF) || isEmpty(passwordTxtF)) {
            JOptionPane.showMessageDialog(this, "All fields are reuqired.", "Error", JOptionPane.ERROR_MESSAGE);
            
            return;
        }

        //create a store object and share it between all frames 
        //get the text from textfiled usin getText() msg
        String userName = userNameTxtF.getText();
        char[] pass = passwordTxtF.getPassword();
        String password = new String(pass);
        
        boolean isValid = currentStore.login(userName, password);
        
        if (isValid) {

            //retrive the customer who logged in 
            Customer[] customers = currentStore.getUsers();
            
            Customer loggedInCustomer = null;
            
            for (Customer cus : customers) {
                if (cus != null) {
                    
                    if (cus.getID().equals(userName)) {
                        loggedInCustomer = cus;
                    }
                }
                
            }
            
                

            //open the Frame and send the object of the logged in customer 
            new OrderManager(currentStore, loggedInCustomer).setVisible(true);
          
            
            
            
            this.dispose();
        } else {
            
            JOptionPane.showMessageDialog(this, "Invalid Login Information , Try again.", "Login Failed", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_loginBtnActionPerformed
    
    private boolean isEmpty(JTextField txtf) {
        
        return txtf.getText().equals("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MAC OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegisterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fullNameTxtF;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JRadioButton loginRB;
    private javax.swing.JPasswordField passwordTxtF;
    private javax.swing.JPasswordField passwordTxtFRegister;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JRadioButton registerRB;
    private javax.swing.JTextField userNameTxtF;
    private javax.swing.JTextField userNameTxtFRegister;
    // End of variables declaration//GEN-END:variables
}
